
sudo: false
language: go
go: 
  - 1.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
  env: GO111MODULE=on
before_install:
    - go get -u github.com/gorilla/mux
script:
    - go get -t -v ./...
    - diff -u <(echo -n) <(gofmt -d -s .)
    - go tool vet .
    - go test -v -race ./...
    - go build /app_1/app1.go
    - go test /app_1/app1.go